# Generated by Django 5.2.4 on 2025-07-28 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=20)),
                ('Sage', models.IntegerField()),
                ('Scontact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20)),
                ('texperience', models.IntegerField()),
                ('texperties', models.CharField(max_length=20)),
                ('tcontact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='joinclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('slot', models.TimeField()),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.students')),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.teachers')),
            ],
            options={
                'unique_together': {('teachers', 'slot')},
            },
        ),
    ]
